[build]
  publish = "."
  command = ""

# 🔥 force root-like routing (hlavní fix)
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

# 🧠 fallback pro SPA (kdyby ses někdy dostal do routingu)
[[redirects]]
  from = "/*"
  to = "/home/home.html"
  status = 200
  force = false

[[redirects]]
  from = "/Projekty/FILM/*"
  to = "/Projekty/FILM/film.html"
  status = 200
